# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQ74yiSjtuqCeURRTepnxBerYEyvXaMy
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install gdown
!gdown --id <your_file_id>

import tensorflow as tf
model = tf.keras.models.load_model("drive/MyDrive/garbage_classifier.h5")
model.summary()

import gradio as gr
import tensorflow as tf
import numpy as np
from PIL import Image

# Load your trained model
MODEL_PATH = "drive/MyDrive/garbage_classifier.h5"   # make sure this file exists in repo or add download code
model = tf.keras.models.load_model(MODEL_PATH)

# Your class names (adjust if needed)
class_names = ["cardboard", "glass", "metal", "paper", "plastic", "trash"]

def predict_gradio(img: Image.Image):
    # Preprocess image
    img = img.convert("RGB").resize((224, 224))
    arr = np.array(img) / 255.0
    arr = np.expand_dims(arr, 0)   # shape (1,224, 224,3)

    # Predict
    preds = model.predict(arr)[0]
    return {class_names[i]: float(preds[i]) for i in range(len(class_names))}

# Build UI
demo = gr.Interface(
    fn=predict_gradio,
    inputs=gr.Image(type="pil"),
    outputs=gr.Label(num_top_classes=3),
    title="♻️ Waste Classifier",
    description="Upload a waste image, and the model predicts its category."
)

if __name__ == "__main__":
    demo.launch()









